index:
    path: /
    defaults:
        _controller: PGPlatformBundle:Default:index

pg_platform:
    resource: "@PGPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform

pg_user:
    resource: "@PGUserBundle/Resources/config/routing.yml"
    prefix:   /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"