services:
    app.roles:
        class: PG\UserBundle\Service\RolesHelper
        arguments: ["%security.role_hierarchy.roles%"]

    app.form.user:
        class: PG\UserBundle\Form\UserType
        arguments: ["%fos_user.model.user.class%", "@app.roles"]
        tags:
            - { name: form.type, alias: app_unused_registration }

    app.form.registration:
        class: PG\UserBundle\Form\RegistrationType
        arguments: ["%fos_user.model.user.class%", "@app.roles"]
        tags:
            - { name: form.type, alias: app_user_registration }

    app.form.profile:
        class: PG\UserBundle\Form\ProfileType
        arguments: ["%fos_user.model.user.class%"]
        tags:
            - { name: form.type, alias: app_user_profile }