services:
    pg_platform.email.operation_mailer:
         class: PG\PlatformBundle\Email\OperationMailer
         arguments:
             - "@mailer"

    oc_platform.doctrine_listener.operation_creation:
         class: PG\PlatformBundle\DoctrineListener\OperationCreationListener
         arguments:
             - "@pg_platform.email.operation_mailer"
         tags:
             - { name: doctrine.event_listener, event: postPersist }
