services:
    pg_platform.email.command_mailer:
         class: PG\PlatformBundle\Email\CommandMailer
         arguments:
             - "@mailer"

    pg_platform.doctrine_listener.command_creation:
         class: PG\PlatformBundle\DoctrineListener\CommandCreationListener
         arguments:
             - "@pg_platform.email.command_mailer"
         tags:
             - { name: doctrine.event_listener, event: postPersist }
