<?php

namespace PG\PlatformBundle\Repository;
use PG\UserBundle\Entity\User;

/**
 * CommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandRepository extends \Doctrine\ORM\EntityRepository
{
    public function findWithProductsCommand($id) {
        $qb = $this->createQueryBuilder('c')
            ->where('c.id = :id')
            ->setParameter('id', $id)
            ->leftJoin('c.products', 'products')
            ->addSelect('products');

        return $qb->getQuery()->getResult();
    }

    public function findByClientAndDate(User $client, \DateTime $date) {
        $qb = $this->createQueryBuilder('c');

        $qb->where('c.client = :client')
            ->setParameter('client', $client)
            ->andWhere('c.date = :date')
            ->setParameter('date', $date);

        return $qb->getQuery()->getResult();
    }
}
