<?php

namespace PG\PlatformBundle\Repository;

/**
 * OperationProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperationProductRepository extends \Doctrine\ORM\EntityRepository
{
}
