<?php

namespace PG\PlatformBundle\Repository;

/**
 * ProductCommandRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCommandRepository extends \Doctrine\ORM\EntityRepository
{
}
