<?php

namespace PG\PlatformBundle\Repository;

/**
 * ProductQuantityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductQuantityRepository extends \Doctrine\ORM\EntityRepository
{
}
